### ISSUE TITLE
Hilos con Windows Forms

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-equipo-mad#1]
[Actividad 9 práctica de Hilos con Windows Forms.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-equipo-mad/files/15126129/Actividad.9.practica.de.Hilos.con.Windows.Forms.pdf)

Integrantes:
Marlene Maricela Osorio Ramírez
Adriana Hernández Martínez 
Daniel Velasco López

**Comment by Ariadnamonserrat10** [comment]
20 de 20 Cumple con cada dato mencionado dentro de la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
